- name: 'To remove a SNMP package from the system'
  hosts: all
  user: ansadm
  become: yes
  become_method: sudo
  tasks:
  
  - name: 'Disable & Stop SNMPD Service'
    service:
     name: snmpd
     enabled: no
     state: stopped

  - name: 'Remove SNMP package & its repositories from the system'
    yum:
     name: net-snmp
     state: absent
