- name: To uninstall multiple packages on a system
  hosts: all
  user: ansadm
  become: yes
  become_method: sudo
  tasks:
   - vars:
      serv: [httpd, vsftpd, snmpd]

     service:
      name: "{{ item }}"
      state: stopped
      enabled: no
     with_items: "{{ serv }}"

   - vars:
      pkgs: [httpd, vsftpd, net-snmp]

     yum:
      name: "{{ item }}"
      state: absent
     with_items: "{{ pkgs }}"
